### ISSUE TITLE
DefaultXMLInstantiator naming error with a tag named 'File'

### ISSUE THREAD

**Issue by jkugs** [mthiede/rgen#19]
When instantiating a model from an xml file that includes a tag named `File` using `DefaultXMLInstantiator`, the program crashes. I believe this is due to line 56 in default_xml_instantiator.rb: `mod.const_get(class_name).new`. The method call: `const_get` will, by default, also searchn up the ancestral chain. When I set the inherit flag to false: `mod.const_get(class_name, false).new`, the model was instantiated correctly.

**Comment by mthiede** [comment]
merged pull request
